Reorganize
arfc/d3ploy pull request #127
Opened 2018-11-10 19:39 UTC by jbae11

This pr does:
* organize test files
* separate test files from example input files
* pep8 issues for all python files (didn't solve E501 -line too long)

2018-11-19 20:22 UTC, gwenchee requested changes
Other than the two comments, I think it looks good.

2018-11-19 20:22 UTC, gwenchee commented on .circleci/config.yml
> +                    pytest ./tests/unit_tests/solver_unit_tests.py
```suggestion
                    pytest ./tests/unit_tests/deploy_solver_unit_tests.py
```

2018-11-19 20:22 UTC, gwenchee commented on .circleci/config.yml
> +                    pytest ./tests/NO_fleet_unit_tests.py
```suggestion
                    pytest ./tests/integration_unit_tests/NO_fleet_unit_tests.py
```

2018-11-20 20:00 UTC, gwenchee commented
This PR addresses https://github.com/ergs/d3ploy/issues/123

2018-11-20 20:11 UTC, FlanFlanagan reviewed
Seems like mostly pep8 stuff. 

But the changes look good to me.  I think we can merge when it passes tests.

2018-11-20 20:20 UTC, merged