Decomm
arfc/d3ploy pull request #230
Opened 2019-04-19 04:40 UTC by FlanFlanagan

To tackle #11

2019-04-19 04:40 UTC, pep8speaks commented
Hello @FlanFlanagan! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`d3ploy/demand_driven_deployment_inst.py`](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py):

> [Line 162:6](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L162): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 162:6](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L162): [E113](https://duckduckgo.com/?q=pep8%20E113) unexpected indentation
> [Line 167:5](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L167): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 176:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L176): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 176:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L176): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 273:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L273): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 273:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L273): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 274:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L274): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 274:2](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L274): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 275:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L275): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 275:3](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L275): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 275:11](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L275): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 275:38](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L275): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 276:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L276): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 276:2](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L276): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 277:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L277): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 277:3](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L277): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 277:11](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L277): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 278:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/demand_driven_deployment_inst.py#L278): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs

* In the file [`d3ploy/solver.py`](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py):

> [Line 176:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L176): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 179:24](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L179): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 185:52](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L185): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 189:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L189): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 196:46](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L196): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 203:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L203): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 216:64](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L216): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 217:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L217): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 217:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L217): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs
> [Line 217:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L217): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 218:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L218): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 218:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L218): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 218:1](https://github.com/arfc/d3ploy/blob/d554e383f05f1b102444f56fd9b4fa6342204e64/d3ploy/solver.py#L218): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2019-04-19 15:37 UTC, gwenchee commented
I pulled down your branch, ran `python setup.py install` and tried running the `linear_pow_loss.xml` file, and it throws an error of `no module found for path libd3ploy.demand_driven_deployment_inst.so`

2019-04-19 16:19 UTC, gwenchee requested changes

2019-04-19 16:19 UTC, gwenchee commented on d3ploy/demand_driven_deployment_inst.py
> +     os_int = ts.Int(
```suggestion
    os_int = ts.Int(
```

2019-04-19 16:19 UTC, gwenchee commented on d3ploy/demand_driven_deployment_inst.py
> +     os_int = ts.Int(
There was a unwanted space there

2019-04-19 16:19 UTC, gwenchee commented on d3ploy/demand_driven_deployment_inst.py
> +	self.commod_mins = {}
There is also unwanted space here.

2019-04-25 20:23 UTC, gwenchee commented
I pulled the branch and reinstalled d3ploy but it doesn't pass the pytest.

2019-04-26 14:18 UTC, katyhuff commented
@gwenchee can you copy/paste the output of the failed test(s) so that @FlanFlanagan knows which are failing?

2019-04-26 14:21 UTC, FlanFlanagan commented
This is still in my queue, trying to fix the cyclus nosttest segfault right now.

2019-04-26 15:05 UTC, gwenchee commented
So i looked again and the pytest are failing because of d3ploy not properly installing. Seems like a syntax error: 
![image](https://user-images.githubusercontent.com/29397884/56817241-d4c2ab00-680a-11e9-9684-a457828ab26b.png)

2019-04-26 15:17 UTC, FlanFlanagan commented
That's odd. I'm not getting that. I didn't even touch line 226 in supply_driven

2019-04-26 15:34 UTC, robfairh commented
I am getting a similar error
![image](https://user-images.githubusercontent.com/43791150/56819188-d8f0c780-680e-11e9-9d15-7fdf6a0da4a8.png)

2019-04-26 15:38 UTC, robfairh commented
I've no idea what happened, I could see that you didn't touch those lines, but there is an inconsistency with the use of tabs and spaces in those lines. Once fixed, it should compile.
Did you get those files from the last version of master?

2019-04-26 15:39 UTC, gwenchee commented
Perhaps update the `decomm` branch with the current arfc/master because it seems to be behind?

2019-04-26 16:02 UTC, katyhuff requested changes
I have only reviewed the solver.py file, but I'm finding some things that definitely won't work.

2019-04-26 16:02 UTC, katyhuff commented on d3ploy/demand_driven_deployment_inst.py
> +        doc="The number minimum capacities over supply limit",
With this description, it's confusing what the unit is. by "number minimum capacities" do you mean "number of facilities of this type, at their minimum possible capacity" ? Please simplify or clarify this doc.

2019-04-26 16:02 UTC, katyhuff commented on d3ploy/demand_driven_deployment_inst.py
> +	    self.commod_mins = {}
is there an indentation problem here?

2019-04-26 16:02 UTC, katyhuff commented on d3ploy/solver.py
> +     Parameters:
indentation issue?

2019-04-26 16:02 UTC, katyhuff commented on d3ploy/solver.py
> +    commod_min: dictionary
The variable descriptions in this docstring could use more detail... minimum commod production allowed or minimum commod production observed? Is this a controlled variable or an observed variable?

2019-04-26 16:02 UTC, katyhuff commented on d3ploy/solver.py
> +                commod_min[commod] = dic['cap']
I'm not usually a huge fan of lambdas, because they're confusing, but I think you can reduce the number of redundant for loops with a combination of the min function and a lambda.

The whole function can be:
```python
for commod in commod_dict.keys():
  commod_min[commod] = min(commod_dict[commod].keys(), key=lambda x:commod_dict[commod][x]['cap'])
return commod_min
```

(x is fac, basically...)

2019-04-26 16:02 UTC, katyhuff commented on d3ploy/solver.py
> +    for fac, dic in commod_min[commod]:
This function will fail. `commod_min` is not defined in this scope. 
Maybe you meant `commod_dict` ...

2019-04-26 16:02 UTC, katyhuff commented on d3ploy/solver.py
> +        facs.append(list(fac_mins.keys())[list(fac_mins.values()).index(i)])
this seems redundant....

2019-04-26 16:04 UTC, gwenchee commented
Current error: 
`
gwenchee ~/github/d3ploy (decom2) $ python setup.py install
running install
running build
running build_py
package init file 'd3ploy/__init__.py' not found (or not a regular file)
package init file 'd3ploy/__init__.py' not found (or not a regular file)
running install_lib
byte-compiling /home/gwenchee/anaconda3/lib/python3.6/site-packages/d3ploy/demand_driven_deployment_inst.py to demand_driven_deployment_inst.cpython-36.pyc
Sorry: TabError: inconsistent use of tabs and spaces in indentation (demand_driven_deployment_inst.py, line 237)
byte-compiling /home/gwenchee/anaconda3/lib/python3.6/site-packages/d3ploy/supply_driven_deployment_inst.py to supply_driven_deployment_inst.cpython-36.pyc
Sorry: TabError: inconsistent use of tabs and spaces in indentation (supply_driven_deployment_inst.py, line 226)
running install_egg_info
Removing /home/gwenchee/anaconda3/lib/python3.6/site-packages/d3ploy-0.0.1-py3.6.egg-info
Writing /home/gwenchee/anaconda3/lib/python3.6/site-packages/d3ploy-0.0.1-py3.6.egg-info
`

2019-05-28 15:41 UTC, katyhuff commented
@FlanFlanagan What's the status of this?

2019-06-29 15:28 UTC, katyhuff commented on d3ploy/demand_driven_deployment_inst.py
> +<<<<<<< HEAD
cruft from merge conflict...

2019-06-29 15:28 UTC, katyhuff commented on d3ploy/solver.py
> +def decommission(agent, commod_dict, diff, commod):
needs docstring

2019-06-29 15:29 UTC, katyhuff commented on d3ploy/supply_driven_deployment_inst.py
> +
only one blank line if the functions are not in global scope.
```suggestion
```

2019-06-29 16:58 UTC, katyhuff commented on d3ploy/supply_driven_deployment_inst.py
> +
@FlanFlanagan

2019-07-05 16:17 UTC, katyhuff commented
@FlanFlanagan Can you please move this PR forward?

2019-07-16 06:41 UTC, katyhuff commented
@FlanFlanagan Thanks for moving this forward. There are conflicts in this PR. Can you resolve them?

2019-07-16 13:04 UTC, FlanFlanagan commented
Yep!

2019-07-19 15:52 UTC, FlanFlanagan commented
After working through this a while, I've discovered that Cyclus does not allow the user to modify the lifetime of a facility once built. Or rather there is a function to do it, but it just throws an error. 

I'm modifying Cyclus to allow for this. Since we're time crunched I'll just support another branch until we can discuss it at the next cyclus meeting.

2019-08-02 16:04 UTC, katyhuff commented
@FlanFlanagan How are the Cyclus modifications going -- is there a PR to review over there?

2019-08-09 05:17 UTC, FlanFlanagan commented
Still a WIP but as of 5 minutes ago I have a working cyclus branch and a d3ploy branch. Need to add tests, but it appears to be decommissioning.

2019-08-30 16:46 UTC, gwenchee requested changes
Could you add an integration test for the decommissioning capability?

2019-08-30 16:46 UTC, gwenchee commented on .cache/v/cache/lastfailed
> +}
Perhaps, remove this file?

2019-08-30 16:46 UTC, gwenchee commented on d3ploy/demand_driven_deployment_inst.py
> +        print(time)
remove all the print statements in this file?

2019-08-30 16:46 UTC, gwenchee commented on d3ploy/solver.py
> +    """ Decommissions the oldest archetypes that produce
```suggestion
    """ Decommissions the oldest prototypes that produce
```

2019-09-02 17:16 UTC, FlanFlanagan commented
> Could you add an integration test for the decommissioning capability?

There is one?

2019-09-03 15:25 UTC, gwenchee commented
Yup, i see the test in the latest commit. Thanks @FlanFlanagan

2019-09-06 15:39 UTC, gwenchee commented
Could you add the decommissioning test into the CI list of tests? @FlanFlanagan

2019-09-06 16:00 UTC, gwenchee requested changes
I have 2 questions. 
1) In `loss.xml`, you didn't deploy a sink facility. And so, when the reactor facilities are decommissioned, do they decommission with all their spent fuel? Where does it go? 
2) I resinstalled cyclus with your `life_time` branch and reinstalled d3ploy with your `decomm` branch and tried running the `decommission_test.py` pytest and it didn't pass. This was the error: 

```
(base) gwenchee@gwenchee-Precision-Tower-3420:~/github/d3ploy/tests/integration_tests$ pytest decommission_test.py 
============================================================= test session starts ==============================================================
platform linux -- Python 3.6.7, pytest-5.1.2, py-1.8.0, pluggy-0.12.0
rootdir: /home/gwenchee/github/d3ploy
plugins: openfiles-0.4.0, remotedata-0.3.1, arraydiff-0.3, doctestplus-0.3.0
collected 1 item                                                                                                                               

decommission_test.py F                                                                                                                   [100%]

=================================================================== FAILURES ===================================================================
______________________________________________________________ test_decommission _______________________________________________________________

    def test_decommission():
        output_ = 'POWER.txt'
        input_path = os.path.abspath(__file__)
        find = 'd3ploy/'
        indx = input_path.rfind('d3ploy/')
        input_ = input_path.replace(
            input_path[indx + len(find):], 'input/loss.xml')
        s = subprocess.check_output(['cyclus', '-o', output_, input_],
                                    universal_newlines=True, env=ENV)
        with open('POWER.txt') as f:
>           lines = f.readlines()

decommission_test.py:39: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <encodings.utf_8.IncrementalDecoder object at 0x7f2c6a8c25f8>
input = b'SQLite format 3\x00\x10\x00\x01\x01\x00@  \x00\x00\x00*\x00\x00\x0eK\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00)\x0...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x16\x819\x00\x00\x00\x15l'
final = False

    def decode(self, input, final=False):
        # decode input (taking the buffer into account)
        data = self.buffer + input
>       (result, consumed) = self._buffer_decode(data, self.errors, final)
E       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfb in position 106: invalid start byte

../../../../anaconda3/lib/python3.6/codecs.py:321: UnicodeDecodeError
============================================================== 1 failed in 5.71s ===============================================================
```

2019-09-06 16:00 UTC, gwenchee commented on input/loss.xml
> +              <capacity>50</capacity>
You defined power capacity for reactor1 as 1MW in line 69?

2019-09-06 16:00 UTC, gwenchee commented on input/loss.xml
> +              <capacity>10000</capacity>
You defined source throughput as 10kg in line 34?

2019-09-06 16:00 UTC, gwenchee commented on tests/integration_tests/decommission_test.py
> +""" This python file contains tech pref capability tests for TimeSeriesInst
Update this documentation?

2019-09-06 16:12 UTC, kipk49 commented on d3ploy/demand_driven_deployment_inst.py
> +        doc="The number facilities over capacity " +
```suggestion
        doc="The number of facilities over capacity " + 
```

2019-09-06 16:14 UTC, kipk49 commented on d3ploy/supply_driven_deployment_inst.py
> +        doc="The number facilities over capacity " +
```suggestion
        doc="The number of facilities over capacity " + 
```

2019-09-06 19:25 UTC, FlanFlanagan commented
Okay, should be good on the d3ploy side. However, cycamore needs to be updated for the test to pass I believe. 

It's passing on my machine with the new PR I put into cyacmore. 

A side note, and this is very important, with the installed capacity change if you have any facilities in your institution that are not being tracked by D3ploy, it will cause d3ploy to fail.

2019-09-18 03:29 UTC, katyhuff commented
@gwenchee Has @FlanFlanagan handled your comments?

2019-09-27 20:40 UTC, katyhuff commented
@pep8speaks pep8ify

2019-09-27 20:40 UTC, pep8speaks commented
Here you go with [the Pull Request](https://github.com/FlanFlanagan/d3ploy/pull/2) ! The fixes are suggested by [autopep8](https://github.com/hhatto/autopep8).

 @katyhuff @FlanFlanagan

2019-09-27 20:41 UTC, gwenchee commented
@FlanFlanagan I don't think you addressed the review comments I made previously.

2019-09-27 20:42 UTC, katyhuff commented
> A side note, and this is very important, with the installed capacity change if you have any facilities in your institution that are not being tracked by D3ploy, it will cause d3ploy to fail.

This seems bad.

2019-09-30 15:30 UTC, FlanFlanagan commented
It was bad. Which is why I asked @gwenchee to fix it. Since the installed capacity was part of her work. I didn't see any movement so it is currently fixed in this PR. 

It looks like I did address your comments. I'm not sure what I missed but I'm happy to fix it.

2019-09-30 15:31 UTC, FlanFlanagan commented
Ah, sorry. I didn't mark them as resolved! Sorry!

2019-09-30 18:53 UTC, katyhuff commented
ok! @gwenchee @robfairh @kipk49 Can someone take a look and review?

2019-09-30 19:47 UTC, robfairh commented
decommision_test fails on my machine. Do you have the same issue @FlanFlanagan ??

2019-09-30 19:56 UTC, robfairh commented
I also tried running input/decommission.xml and I got this:
```
roberto ~/github/d3ploy/input (decomm) $ cyclus decommission.xml 
              :                                                               
          .CL:CC CC             _Q     _Q  _Q_Q    _Q    _Q              _Q   
        CC;CCCCCCCC:C;         /_\)   /_\)/_/\\)  /_\)  /_\)            /_\)  
        CCCCCCCCCCCCCl       __O|/O___O|/O_OO|/O__O|/O__O|/O____________O|/O__
     CCCCCCf     iCCCLCC     /////////////////////////////////////////////////
     iCCCt  ;;;;;.  CCCC                                                      
    CCCC  ;;;;;;;;;. CClL.                          c                         
   CCCC ,;;       ;;: CCCC  ;                   : CCCCi                       
    CCC ;;         ;;  CC   ;;:                CCC`   `C;                     
  lCCC ;;              CCCC  ;;;:             :CC .;;. C;   ;    :   ;  :;;   
  CCCC ;.              CCCC    ;;;,           CC ;    ; Ci  ;    :   ;  :  ;  
   iCC :;               CC       ;;;,        ;C ;       CC  ;    :   ; .      
  CCCi ;;               CCC        ;;;.      .C ;       tf  ;    :   ;  ;.    
  CCC  ;;               CCC          ;;;;;;; fC :       lC  ;    :   ;    ;:  
   iCf ;;               CC         :;;:      tC ;       CC  ;    :   ;     ;  
  fCCC :;              LCCf      ;;;:         LC :.  ,: C   ;    ;   ; ;   ;  
  CCCC  ;;             CCCC    ;;;:           CCi `;;` CC.  ;;;; :;.;.  ; ,;  
    CCl ;;             CC    ;;;;              CCC    CCL                     
   tCCC  ;;        ;; CCCL  ;;;                  tCCCCC.                      
    CCCC  ;;     :;; CCCCf  ;                     ,L                          
     lCCC   ;;;;;;  CCCL                                                      
     CCCCCC  :;;  fCCCCC                                                      
      . CCCC     CCCC .                                                       
       .CCCCCCCCCCCCCi                                                        
          iCCCCCLCf                                                           
           .  C. ,                                                            
              :                                                               
/home/roberto/anaconda3/lib/python3.6/site-packages/sklearn/externals/six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
/home/roberto/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
 ERROR(core  ):SQL error [INSERT INTO AgentState_d3ploy_demand_driven_deployment_inst_DemandDrivenDeploymentInstInfo VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);]: table AgentState_d3ploy_demand_driven_deployment_inst_DemandDrivenDeploymentInstInfo has 20 columns but 22 values were supplied
```

2019-09-30 19:57 UTC, katyhuff commented
@FlanFlanagan @robfairh  it seems like this new decommission_test.py isn't being included in the CI. Please add this to CI in the "full integration test" part and see if it passes on CI. 

Also -- rather than running specific test_*.py files, why not run py.test in the directory?

2019-09-30 20:25 UTC, robfairh commented
It passes the CI in #292 . I am trying to figure out why the test don't pass on my local.

2019-09-30 20:57 UTC, robfairh commented
I updated Cyclus and Cycamore and now the tests for decommisioning are passing.

2019-09-30 21:36 UTC, FlanFlanagan commented
@katyhuff shouldn't this go with the other functionality tests? It is being run there, I just looked at those tests and it is listed. 

I think the failures that @robfairh were seeing were because he did not have an updated cyclus/cycamore. If the structure of the testing is inaccurate we can fix that but I think that should be a separate PR as the testing update here matches previous style.

2019-09-30 21:38 UTC, katyhuff commented
Ah. Yes, I see. I expected it in the "integration tests" so I looked there and didn't see it, but you're right, it's in "functionality tests". Thanks @FlanFlanagan

2019-10-01 15:53 UTC, robfairh commented
I ran input/decommision.xml and I got this plot for power:
![decom2-power](https://user-images.githubusercontent.com/43791150/65978428-4c8ba600-e439-11e9-8121-787c0399ce69.png)

I also added the deployment of 'source' facilities and 'Sinks' and this are the plots for them:
![test1](https://user-images.githubusercontent.com/43791150/65978512-7513a000-e439-11e9-9078-9455aab910a0.png)
![test2](https://user-images.githubusercontent.com/43791150/65978539-8197f880-e439-11e9-9ffa-c017018f50c7.png)

The decommission capability seems to be working. I am ready to merge this PR when @FlanFlanagan  merges the PR that solves the PEP8 issues https://github.com/FlanFlanagan/d3ploy/pull/2.

2019-10-01 17:33 UTC, FlanFlanagan commented
Pep 8 taken care of! @robfairh

2019-10-01 17:40 UTC, robfairh commented
Cool! Would it be possible to add a new variable to activate or deactivate the decommissioning capability? Like record: when it is 0, it is not used, and when it is 1, it is used. Sorry @FlanFlanagan this is the last thing.

2019-10-01 19:11 UTC, FlanFlanagan commented
Yeah, is there a reason you want it turned off?

2019-10-01 20:44 UTC, robfairh commented
Yeah, so it is backward compatible with the all the inputs we already have.

2019-10-01 22:50 UTC, FlanFlanagan commented
Okay, I adjusted the default os_time

2019-10-01 22:59 UTC, merged