Constraint bug
arfc/d3ploy pull request #272
Opened 2019-07-13 22:22 UTC by gwenchee

This PR addresses https://github.com/arfc/d3ploy/issues/271

2019-07-13 22:22 UTC, pep8speaks commented
Hello @gwenchee! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`d3ploy/solver.py`](https://github.com/arfc/d3ploy/blob/07621361f2380f652d54b0402805858ab2811cfe/d3ploy/solver.py):

> [Line 49:80](https://github.com/arfc/d3ploy/blob/07621361f2380f652d54b0402805858ab2811cfe/d3ploy/solver.py#L49): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 63:80](https://github.com/arfc/d3ploy/blob/07621361f2380f652d54b0402805858ab2811cfe/d3ploy/solver.py#L63): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 66:80](https://github.com/arfc/d3ploy/blob/07621361f2380f652d54b0402805858ab2811cfe/d3ploy/solver.py#L66): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 71:80](https://github.com/arfc/d3ploy/blob/07621361f2380f652d54b0402805858ab2811cfe/d3ploy/solver.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

2019-07-15 12:31 UTC, robfairh commented on d3ploy/supply_driven_deployment_inst.py
> +        self.constraint_toggle = {}
We don't use this in the end, right?

```suggestion
```

2019-07-15 12:31 UTC, robfairh requested changes
Other than that extra variable, looks good!

2019-07-15 13:46 UTC, gwenchee commented
I removed the extra variable @robfairh

2019-07-15 16:42 UTC, robfairh approved these changes
Looks good!

2019-07-15 16:42 UTC, merged