Allows for limited-time supply buffers
arfc/d3ploy pull request #284
Opened 2019-07-29 22:57 UTC by sonatav2

Introduces a `supply_buffer_length` parameter which can be set to the maximum time step up to which you would like to include a supply buffer. This was developed for scenarios such as the eg01-eg30 transition scenario, where waiting to deploy new reactors until the previous reactors begin decommissioning (causing the power supply to fall) results in a period of undersupply during the transition. This undersupply can be minimized by using a combination of facility_preference and a limited-time buffer to deploy new reactors shortly before supply falls below demand.

Example: If the initial facilities will begin decommissioning at time step 950, a combination of facility_preference `(t-940)` and a 30% power supply buffer with `supply_buffer_length = 950` can be implemented to trigger an initial deployment of reactors at time step 941. 

Without `supply_buffer_length`, the supply buffer would continue to effect the demand equation through the end of the simulation, and there would be an overdeployment of reactors. This allows the user to trigger pre-transition deployment without permanently effecting the demand for the commodity.

2019-07-29 22:57 UTC, pep8speaks commented
Hello @sonatav2! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`d3ploy/demand_driven_deployment_inst.py`](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/d3ploy/demand_driven_deployment_inst.py):

> [Line 169:80](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/d3ploy/demand_driven_deployment_inst.py#L169): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 249:17](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/d3ploy/demand_driven_deployment_inst.py#L249): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

* In the file [`d3ploy/deployment_inst.py`](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/d3ploy/deployment_inst.py):

> [Line 80:1](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/d3ploy/deployment_inst.py#L80): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 90:23](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/d3ploy/deployment_inst.py#L90): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

* In the file [`tests/integration_tests/buffer_test.py`](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/tests/integration_tests/buffer_test.py):

> [Line 727:80](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/tests/integration_tests/buffer_test.py#L727): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 873:1](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/tests/integration_tests/buffer_test.py#L873): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 876:80](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/tests/integration_tests/buffer_test.py#L876): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> [Line 877:80](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/tests/integration_tests/buffer_test.py#L877): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 903:21](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/tests/integration_tests/buffer_test.py#L903): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 904:80](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/tests/integration_tests/buffer_test.py#L904): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 906:21](https://github.com/arfc/d3ploy/blob/3adca18d702c501eb2f1772f8bc240b83c4b5a4e/tests/integration_tests/buffer_test.py#L906): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2019-07-30 00:21 UTC, katyhuff requested changes
looks good. one minor comment about global scope in the tests.

2019-07-30 00:21 UTC, katyhuff commented on tests/integration_tests/buffer_test.py
> +# -------------------------------------------------------------------------- #
I prefer not having this kind of variable defined at the global scope. Ideally, this template would be in a setup function (see http://doc.pytest.org/en/latest/fixture.html ) or if it's only used in one test, put it in the test function itself.

2019-07-30 00:21 UTC, katyhuff commented on tests/integration_tests/buffer_test.py
> +nobuf_template_length = copy.deepcopy(TEMPLATE_length)
same as above comment regarding fixtures.

2019-07-30 00:21 UTC, katyhuff commented on tests/integration_tests/buffer_test.py
> +yesbuf_template_length = copy.deepcopy(TEMPLATE_length)
same as above comment regarding fixtures.

2019-09-18 03:28 UTC, katyhuff commented
@robfairh @gwenchee @FlanFlanagan @sonatav2 

Can someone bring these improvements in and bring this PR to a close?

2019-09-19 16:23 UTC, FlanFlanagan commented
@katyhuff 

It looks like @sonatav2 followed the procedure from the other TEMPLATE in the same document. Do you want that updated as well?

2019-09-20 20:59 UTC, FlanFlanagan commented
I'll be taking a crack at this! Thanks!

2019-09-27 05:29 UTC, FlanFlanagan commented
I made changes to this file, but I don't have the ability to push to her branch? Should I make a new PR?

2019-09-27 13:53 UTC, robfairh commented
Yes, do it @FlanFlanagan

2019-09-27 20:44 UTC, katyhuff commented
This seems good -- @FlanFlanagan @sonatav2 Since this one is passing the tests, is it superior to #290 .

2019-09-30 15:40 UTC, FlanFlanagan commented
This is superior! I'll close mine!

2020-01-20 17:22 UTC, robfairh commented
This version was never fully implemented and it is no longer needed.

2020-01-20 17:22 UTC, closed without merging