backsteps
arfc/d3ploy pull request #286
Opened 2019-08-05 21:07 UTC by robfairh

Addresses #285

2019-08-05 21:20 UTC, gwenchee requested changes
Nice catch!

2019-08-05 21:20 UTC, gwenchee commented on d3ploy/NO_solvers.py
> +    x = np.average(supply[-1*back_steps:])
What happens if the supply length is shorter than backsteps val?

2019-08-05 21:20 UTC, gwenchee commented on d3ploy/NO_solvers.py
> +    x = np.average(supply[-1*back_steps:])
Should the if statement be kept?

2019-08-05 22:08 UTC, robfairh commented on d3ploy/NO_solvers.py
> +    x = np.average(supply[-1*back_steps:])
the if statement is redundant. If the array has a length of 5 and you say 
```
supply = supply[-10:]
```
it will take just the 5 elements of the array.

If you see arma  and arch, they don't have the if statement and they work as well.

2019-08-06 14:05 UTC, gwenchee commented on d3ploy/NO_solvers.py
> +    x = np.average(supply[-1*back_steps:])
Oh okay perfect! I just did a little proof of concept in python: 
```
>>> a = [1,2,3]
>>> a[-10:]
[1, 2, 3]```

2019-08-06 14:05 UTC, gwenchee approved these changes
Looks good then.

2019-08-06 14:05 UTC, merged